apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app-api
  name: my-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-api
  template:
    metadata:
      labels:
        app: my-app-api
    spec:
      containers:
        - name: app
          image: launcher.gcr.io/google/nginx1
          ports:
          - containerPort: 80

