apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-ksa
  namespace: "external-secrets"
  annotations:
    iam.gke.io/gcp-service-account: "external-secrets@terraform-dev-abcd.iam.gserviceaccount.com"
