apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      volumes:
      - name: service-account-json
        secret:
          secretName: test-workflow-service-account
          items:
          - key: service_account_json
            path: service_account.json
      containers:
        - name: app
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: service-account-json
              mountPath: /app/credentials
