name: "Terraform CI for staging"

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/staging/**"

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

env:
  terraform-version: 1.1.7
  tfmigrate-version: 0.3.3
  working-directory: terraform/staging
  workload-identity-provider: projects/34389937598/locations/global/workloadIdentityPools/terraform-pool/providers/terraform-gh-provider
  gcp-service-account: terraform@terraform-dev-abcd.iam.gserviceaccount.com

jobs:
  ci:
    name: "Terraform CI"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: "Google Auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ env.workload-identity-provider }}
          service_account: ${{ env.gcp-service-account }}
      - name: "Terraform Plan"
        uses: ./.github/actions/terraform-plan
        id: plan
        with:
          terraform-version: ${{ env.terraform-version }}
          working-directory: ${{ env.working-directory }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-workflow-service-account: ${{ secrets.TF_VAR_TEST_WORKFLOW_SERVICE_ACCOUNT }}
          credentials-json: ${{ secrets.CREDENTIALS_JSON }}
